# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screen_share.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RASO_ScreenShare(object):
    def setupUi(self, RASO_ScreenShare):
        RASO_ScreenShare.setObjectName("RASO_ScreenShare")
        RASO_ScreenShare.setEnabled(True)
        RASO_ScreenShare.resize(1400, 714)
        self.centralwidget = QtWidgets.QWidget(RASO_ScreenShare)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.top_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top_label.sizePolicy().hasHeightForWidth())
        self.top_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.top_label.setFont(font)
        self.top_label.setAutoFillBackground(False)
        self.top_label.setStyleSheet("background-color : rgb(193, 227, 210);")
        self.top_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.top_label.setIndent(-1)
        self.top_label.setObjectName("top_label")
        self.gridLayout.addWidget(self.top_label, 0, 1, 1, 2)
        self.screenShareQuitButton = QtWidgets.QPushButton(self.centralwidget)
        self.screenShareQuitButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.screenShareQuitButton.sizePolicy().hasHeightForWidth())
        self.screenShareQuitButton.setSizePolicy(sizePolicy)
        self.screenShareQuitButton.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.screenShareQuitButton.setFont(font)
        self.screenShareQuitButton.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.screenShareQuitButton.setAutoFillBackground(False)
        self.screenShareQuitButton.setStyleSheet("border: 2px solid red;\n"
"background: rgb(255, 255, 255);")
        self.screenShareQuitButton.setIconSize(QtCore.QSize(16, 16))
        self.screenShareQuitButton.setObjectName("screenShareQuitButton")
        self.gridLayout.addWidget(self.screenShareQuitButton, 1, 1, 1, 1)
        self.screen = QtWidgets.QLabel(self.centralwidget)
        self.screen.setAutoFillBackground(True)
        self.screen.setText("")
        self.screen.setPixmap(QtGui.QPixmap("../../Pictures/Screenshots/스크린샷 2023-06-13 230425.png"))
        self.screen.setScaledContents(True)
        self.screen.setAlignment(QtCore.Qt.AlignCenter)
        self.screen.setObjectName("screen")
        self.gridLayout.addWidget(self.screen, 4, 1, 1, 2)
        self.bottom_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bottom_label.sizePolicy().hasHeightForWidth())
        self.bottom_label.setSizePolicy(sizePolicy)
        self.bottom_label.setAutoFillBackground(False)
        self.bottom_label.setStyleSheet("background-color : rgb(145, 175, 151);")
        self.bottom_label.setAlignment(QtCore.Qt.AlignCenter)
        self.bottom_label.setIndent(-1)
        self.bottom_label.setObjectName("bottom_label")
        self.gridLayout.addWidget(self.bottom_label, 5, 1, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        RASO_ScreenShare.setCentralWidget(self.centralwidget)

        self.retranslateUi(RASO_ScreenShare)
        QtCore.QMetaObject.connectSlotsByName(RASO_ScreenShare)

    def retranslateUi(self, RASO_ScreenShare):
        _translate = QtCore.QCoreApplication.translate
        RASO_ScreenShare.setWindowTitle(_translate("RASO_ScreenShare", "RASO_ScreenShare"))
        self.top_label.setText(_translate("RASO_ScreenShare", "  RASO"))
        self.screenShareQuitButton.setText(_translate("RASO_ScreenShare", "화면공유 종료"))
        self.bottom_label.setText(_translate("RASO_ScreenShare", "@copyright 2023 RASO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RASO_ScreenShare = QtWidgets.QMainWindow()
    ui = Ui_RASO_ScreenShare()
    ui.setupUi(RASO_ScreenShare)
    RASO_ScreenShare.show()
    sys.exit(app.exec_())
